### ISSUE TITLE
Using npm 3.2.x + on Azure?

### ISSUE THREAD

**Issue by ztsmith** [felixrieseberg/azure-npm3#1]
It seems the npm version 3.1.x has problems with node-gyp that affects various packages e.g. babel:
- https://github.com/npm/npm/issues/8878
- https://github.com/nodejs/node-gyp/issues/661
- https://github.com/npm/npm/issues/8921

Npm 3.2.x (or 3.3.x) fixes the issue but it's not available on Azure web apps yet. The only availble version of npm3 is 3.1.0.
I need npm 3.x for the flattened dependencies, but can't use the current version so appear to be stuck at this point.
Any ideas of how this can be worked around? e.g. manually install a local copy of NPM and use that?

**Comment by felixrieseberg** [comment]
Thanks for reporting! There's an obvious fix: We should just update npm on Azure Web Apps ;-)

@davidebbo Can you (or someone in your team) push the latest npm?

**Comment by davidebbo** [comment]
So the latest 3.3.6 would be good?

Any idea why the latest Node 4.2 is still [pointing](https://raw.githubusercontent.com/nodejs/node/v4.2.0/deps/npm/package.json) to 2.14.7 and not some 3.x version?

**Comment by felixrieseberg** [comment]
Yeah, that version would be good. npm is still testing npm 3 - it's super stable, but the Windows-friendly change to install modules flat (and the new multistage installer) could lead to some issues for module developers, so they're giving people some time to adjust to the change.

On Azure, we should probably stick with 2.x as the default, but make the latest 3.x available (because it has so many benefits on Windows)

**Comment by davidebbo** [comment]
Ok, I'll get 3.3.6 deployed.

**Comment by davidebbo** [comment]
Ok, 3.3.6 is now available in Azure Web Apps.

**Comment by lijunle** [comment]
I still see the nodejs/node-gyp#661 with 3.3.6 on Azure. :cry:

**Comment by ztsmith** [comment]
Thanks @davidebbo and @felixrieseberg for the super quick response and action - I have been able to move forward now.

@lijunle Try clearing out your node_modules folder and then re-running `npm install`

**Comment by lijunle** [comment]
@ztsmith Thank you very much! Delete the node_modules folder and re-deploy works great!
