### ISSUE TITLE
NPM versions available on Azure?

### ISSUE THREAD

**Issue by petetnt** [felixrieseberg/azure-npm3#2]
I am trying to get my web app to deploy on Azure and I am running to the long paths issue with npm@2.

Googling around lead me to this repo and other mentions of using `3.1.0`. #1 points to `3.3.6` being available too, but the current stable version is 3.8.1. Any idea how to check on which `npm` versions are available on Azure? 

Pinging @davidebbo too.

**Comment by davidebbo** [comment]
To get the full list of supported Node and npm:
- Go to https://[yoursite].scm.azurewebsites.net/
- Click on 'Runtime versions' under API

**Comment by petetnt** [comment]
Thanks @davidebbo!
